// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WindowsFormsDatagrid;
//
//    var oszlop = Oszlop.FromJson(jsonString);

namespace WindowsFormsDatagrid
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    /*
     * az adatbázis oszlopait az sql-ből le lehet kérdezni a következő lekérdezéssel:
     *  select column_name from information_schema.columns
     *  where table_schema = 'orszagok'
     *  order by table_name,ordinal_position
     * 
     * Az oszlopokat a következő lekérdezéssel lehet lekérdezni:
     *  SHOW FULL COLUMNS FROM orszagok;
     */
    public partial class Oszlop
    {
        [JsonProperty("column_name")]
        public string ColumnName { get; set; }

        [JsonProperty("DATA_TYPE")]
        public string DataType { get; set; }

        [JsonProperty("NUMERIC_PRECISION,")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? NumericPrecision { get; set; }

        [JsonProperty("NUMERIC_SCALE")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? NumericScale { get; set; }

        [JsonProperty("megjegyzés")]
        public string Megjegyzés { get; set; }
        public override string ToString()
        {
            return this.Megjegyzés;
        }
    }

    public partial class Oszlop
    {
        public static Oszlop[] FromJson(string json) => JsonConvert.DeserializeObject<Oszlop[]>(json, WindowsFormsDatagrid.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Oszlop[] self) => JsonConvert.SerializeObject(self, WindowsFormsDatagrid.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();

 
    }
}
